name: cps_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-3.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  get: ^4.6.6
  get_it: ^7.7.0
  http: ^1.2.1
  rxdart: ^0.27.7
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  sqflite_sqlcipher: ^2.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/